# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fib = [1,1]
even_fib = []

while True:
	val = fib[-1] + fib[-2]
	if val % 2 == 0:
		even_fib.append(val)
	fib.append(val)
	if val > 4000000:
		print(fib)
		break
		
print(even_fib)
print(sum(even_fib))
